services:
  - type: web
    name: url-shortener-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production 